import React, { useState, useEffect } from 'react';
import { AuditLog, LogLevel } from '../types';
import { Logger } from '../services/logger';
import { 
  X, 
  Terminal, 
  Trash2, 
  Download, 
  Search, 
  Bug, 
  CheckCircle2, 
  AlertTriangle, 
  AlertCircle, 
  Info,
  RefreshCw
} from 'lucide-react';

interface DebugLogsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const LEVEL_COLORS: Record<LogLevel, { badge: string; text: string; icon: React.ReactNode }> = {
  info: {
    badge: 'bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-900',
    text: 'text-blue-600',
    icon: <Info className="w-3.5 h-3.5" />,
  },
  warn: {
    badge: 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-900',
    text: 'text-amber-600',
    icon: <AlertTriangle className="w-3.5 h-3.5" />,
  },
  error: {
    badge: 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-900',
    text: 'text-rose-600',
    icon: <AlertCircle className="w-3.5 h-3.5" />,
  },
  debug: {
    badge: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-700',
    text: 'text-slate-500',
    icon: <Bug className="w-3.5 h-3.5" />,
  },
};

export const DebugLogsModal: React.FC<DebugLogsModalProps> = ({ isOpen, onClose }) => {
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [levelFilter, setLevelFilter] = useState<'all' | LogLevel>('all');
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (isOpen) {
      setLogs(Logger.getLogs());
      const unsubscribe = Logger.subscribe((updated) => setLogs(updated));
      return () => unsubscribe();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const filteredLogs = logs.filter((log) => {
    if (levelFilter !== 'all' && log.level !== levelFilter) return false;
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        log.action.toLowerCase().includes(q) ||
        log.details.toLowerCase().includes(q) ||
        (log.taskId && log.taskId.toLowerCase().includes(q))
      );
    }
    return true;
  });

  const handleDownloadLogs = () => {
    const text = Logger.exportLogsAsText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `debug-logs-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    Logger.info('DEBUG_LOGS_DOWNLOADED', 'Exported debug logs to plain text file');
  };

  const handleCreateTestLog = () => {
    Logger.debug('TEST_DIAGNOSTIC_TRIGGER', 'Diagnostic ping generated by user for debugging inspection', undefined, {
      screenResolution: `${window.innerWidth}x${window.innerHeight}`,
      online: navigator.onLine,
      timestamp: Date.now(),
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div 
        className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl w-full max-w-3xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
              <Terminal className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-slate-900 dark:text-white">
                Application & Debugging Logs
              </h3>
              <p className="text-[11px] text-slate-500 dark:text-slate-400">
                Persistent local event stream for auditing actions, sync events, and troubleshooting
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Action Controls & Filters */}
        <div className="p-4 border-b border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-800/30 flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-2 flex-1 min-w-[200px]">
            <div className="relative flex-1">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
              <input
                type="text"
                placeholder="Search logs by action or text..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full text-xs pl-8 pr-3 py-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-slate-900 dark:text-white focus:outline-none focus:ring-1 focus:ring-indigo-500"
              />
            </div>

            {/* Level Filter */}
            <select
              value={levelFilter}
              onChange={(e) => setLevelFilter(e.target.value as any)}
              className="text-xs font-medium bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg px-2 py-1.5 text-slate-700 dark:text-slate-300 focus:outline-none"
            >
              <option value="all">All Levels ({logs.length})</option>
              <option value="error">Errors</option>
              <option value="warn">Warnings</option>
              <option value="info">Info</option>
              <option value="debug">Debug</option>
            </select>
          </div>

          {/* Buttons: Test, Download, Clear */}
          <div className="flex items-center gap-1.5">
            <button
              onClick={handleCreateTestLog}
              className="text-xs px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-medium transition flex items-center gap-1"
              title="Add a test log entry"
            >
              <Bug className="w-3.5 h-3.5 text-indigo-500" />
              Test Ping
            </button>
            <button
              onClick={handleDownloadLogs}
              className="text-xs px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-medium transition flex items-center gap-1"
            >
              <Download className="w-3.5 h-3.5" />
              Save .txt
            </button>
            <button
              onClick={() => Logger.clearLogs()}
              className="text-xs px-2.5 py-1.5 rounded-lg border border-rose-200 dark:border-rose-900/60 bg-white dark:bg-slate-800 hover:bg-rose-50 dark:hover:bg-rose-950/40 text-rose-600 dark:text-rose-400 font-medium transition flex items-center gap-1"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Clear
            </button>
          </div>
        </div>

        {/* Log Entries List */}
        <div className="flex-1 overflow-y-auto p-4 font-mono text-xs divide-y divide-slate-100 dark:divide-slate-800/80">
          {filteredLogs.length === 0 ? (
            <div className="py-12 text-center text-slate-400 dark:text-slate-500 font-sans">
              No log entries match your filter.
            </div>
          ) : (
            filteredLogs.map((log) => {
              const style = LEVEL_COLORS[log.level] || LEVEL_COLORS.info;
              const time = new Date(log.timestamp).toLocaleTimeString();
              const date = new Date(log.timestamp).toLocaleDateString();

              return (
                <div key={log.id} className="py-2.5 flex items-start gap-2.5 hover:bg-slate-50/60 dark:hover:bg-slate-800/40 rounded px-1.5 transition">
                  <span className="text-[10px] text-slate-400 shrink-0 select-none pt-0.5" title={log.timestamp}>
                    {time}
                  </span>

                  {/* Level badge */}
                  <span
                    className={`inline-flex items-center gap-1 text-[10px] uppercase font-bold px-1.5 py-0.5 rounded border shrink-0 ${style.badge}`}
                  >
                    {style.icon}
                    {log.level}
                  </span>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-slate-800 dark:text-slate-200">
                        {log.action}
                      </span>
                      {log.taskId && (
                        <span className="text-[10px] bg-slate-100 dark:bg-slate-800 text-slate-500 px-1 rounded">
                          task:{log.taskId}
                        </span>
                      )}
                    </div>
                    <p className="text-slate-600 dark:text-slate-300 break-words mt-0.5 text-[11px] font-sans">
                      {log.details}
                    </p>
                    {log.metadata && (
                      <pre className="mt-1 text-[10px] bg-slate-100 dark:bg-slate-950 p-1.5 rounded overflow-x-auto text-slate-600 dark:text-slate-400">
                        {JSON.stringify(log.metadata, null, 2)}
                      </pre>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Footer info */}
        <div className="px-6 py-3 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 flex items-center justify-between text-[11px] text-slate-500 dark:text-slate-400">
          <span>Stored in browser local storage (`task_manager_debug_logs_v1`)</span>
          <span>{logs.length} / 300 entries stored</span>
        </div>
      </div>
    </div>
  );
};
